### ISSUE TITLE
How do you change the parameter?

### ISSUE THREAD

**Issue by utdrmac** [TezTech/fi-compiler#15]
All fi-compiled code appears to set the parameter as bytes. Can't find in the documentation on how to change this to something else, like natural number.

**Comment by stephenandrews** [comment]
Currently, the parameter will always be bytes. This allows us to prepend a 4byte hex code to determine the entry point, and the remaining bytes are UNPACKed on a per entry basis.

So you can still have an entry that requires a nat, but the parameter required to call the contract will be bytes.

I'm looking at merging a feature I've developed, which allows you to optimize the parameter. So if you have a single entry point, we utilize the actual parameter type instead of bytes (so you could have a contract with parameter of nat)

**Comment by utdrmac** [comment]
Could you leave this open until that feature is merged?
The reason for this issue was that I was trying to re-implement your tezvote (https://tzscan.io/KT1ExvG3EjTrvDcAU7EqLNb77agPa5u6KvnY) code as fi code, and fi doesn't let you change the parameter. So, how would you go about doing this if fi can't change it?

**Comment by stephenandrews** [comment]
Tezvote was written in fi, it was manually written in Michelson.

**Comment by utdrmac** [comment]
Bummer. Would have been a great opportunity to show off Fi. So is it not possible to rewrite tezvote in Fi due to the parameter issue?

**Comment by stephenandrews** [comment]
You can write a smart contract that does something similar to fi, but it will have a different call convention (you'd need to send a set sequence of bytes for each proposal). This is similar to how Solidity works. The benefits is that we can have a unique handle for each entry call.

**Comment by utdrmac** [comment]
I've never heard of Solidity. Fi is literally my first attempt/entry at smart contracts; not just on Tezos, but on any platform. I've been ignoring smart contracts because michelson looks like a foreign language to me. Fi looks like a saving grace because I am quite familiar with JS/Go/PHP/C++. The whole bytes sequences thing makes my head hurt; seems overly complex. If I make a contract and then tell my users they must convert their parameters to byte sequences by using some other tools, etc, etc, they are not going to do that. They will see it overly burdensome and complex. But if parameters can be passed 'as-is' (such as the case with TezVote, literally passing a 1 or 2), that is much easier for them. Looking forward to your feature-merge that allows simple parameters to be passed.
